### PR TITLE
Locking

### LINKED ISSUE #9: Add locking to DiscordSQLHandler
Required for #4.

Preferably this will allow something nice and convenient like:

```python
with sql.lock():
    # do stuff
    # ...
```

### PR DESCRIPTION
**Pull request by ammongit**
Fixes #9 

**Requires #7 to be merged first**

This makes it so `with sql.transaction()` also locks the handle (since you should be doing everything within a transaction anyways)
Since this function now serves double-duty, should we rename it? Like `sql.get_context()` or something.

### CODE REVIEW

**Comment by raylu** [comment]
erm, what is the point of having transactions if you're going to serialize your database access?

**Comment by ammongit** [comment]
So that multiple, related SQL operations apply in one atomic operation.

The locking is necessary because eventually there will be multiple tasks using a shared instance, and neither the instance nor its dbapi internals are thread-safe.

**Comment by raylu** [comment]
but allowing multiple concurrent writes to apply atomically is what transactions do

http://initd.org/psycopg/docs/usage.html#thread-safety
> The Psycopg module and the connection objects are thread-safe: many threads can access the same database either using separate sessions and creating a connection per thread or using the same connection and creating separate cursors. In DB API 2.0 parlance, Psycopg is level 2 thread safe.

https://www.python.org/dev/peps/pep-0249/#threadsafety

you are instead **serializing your writes**, at which point both being async and even having threads becomes completely pointless

**Comment by ammongit** [comment]
The sqlalchemy docs say that their transaction objects are not thread-safe. (I'm not using psycopg directly). It seems from their examples that creating a new transaction in the same connection is for _sub_-transactions, which will not help with parallelism. In this case, locks would not be needed.

Perhaps each `.transaction()` call can create its own connection, and then each could operate independently and asynchronously. Not sure how expensive connections are.

**Comment by raylu** [comment]
not sure what docs you're reading; could you link me to them? sessions are indeed [not thread-safe](http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#is-the-session-thread-safe), but that is why you create one per thread (or just create one in your async handler since we are doing things the silly way. alternatively, use a real async framework like eventlet and get free [scoped sessions](http://docs.sqlalchemy.org/en/latest/orm/contextual.html))

> It seems from their examples that creating a new transaction in the same connection is for sub-transactions, which will not help us here.

??? huh? what are you talking about?

**Comment by ammongit** [comment]
@raylu 
http://docs.sqlalchemy.org/en/latest/core/connections.html#sqlalchemy.engine.Transaction

What that means is that connection is stateful:
```python
conn = # sqlalchemy connection
with conn.begin():
    # do stuff
    with conn.begin():
       # this isn't an independent transaction
       # this is actually a sub-transaction, or a
       # transaction within the first one
```

**Comment by ammongit** [comment]
So based on that I have decided that I will modify the `transactions` branch so that it stores the connection in `_Transaction`, meaning each `with sql.transaction()` it will spawn a separate connection. This should allow for concurrency without needing to lock the full `sql` instance for the full duration of the SQL operation.

**Comment by raylu** [comment]
you have grossly misinterpreted the docs.

`sqlalchemy.engine.Transaction` objects are not thread-safe, meaning they cannot be shared between threads. you must create a transaction for each thread... which is what you are doing, and is fine. you do not need to lock if you have separate transaction objects

it is also possible to have nested transactions. this is... irrelevant to the current situation

**Pull request closed without merging**
